# -*- coding: utf-8 -*-
"""train_and_explain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZbxHZdhKnBB-lTaY60JVkiQAm-Pd1HCk
"""

import pandas as pd
import numpy as np
import xgboost as xgb
import shap
!pip install mlflow
import mlflow
import mlflow.xgboost
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, log_loss
import matplotlib.pyplot as plt
import os

# 1. Generate Synthetic Telematics Data (Allstate Context)
np.random.seed(42)
n_samples = 5000

# Features: Driving behavior & demographics
annual_mileage = np.random.normal(12000, 4000, n_samples)
hard_braking_events = np.random.poisson(3, n_samples)
speeding_events = np.random.poisson(5, n_samples)
driver_age = np.random.randint(18, 75, n_samples)

# Target: Did they file a claim? (Higher risk for young drivers with bad telematics)
risk_score = (hard_braking_events * 0.3) + (speeding_events * 0.2) - (driver_age * 0.05)
probability_of_claim = 1 / (1 + np.exp(-risk_score)) # Sigmoid
filed_claim = np.random.binomial(1, probability_of_claim)

df = pd.DataFrame({
    'annual_mileage': annual_mileage,
    'hard_braking_events': hard_braking_events,
    'speeding_events': speeding_events,
    'driver_age': driver_age,
    'filed_claim': filed_claim
})

X = df.drop('filed_claim', axis=1)
y = df['filed_claim']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. MLOps: Track Experiment with MLflow
mlflow.set_experiment("Allstate_Telematics_Risk")

with mlflow.start_run():
    # Model parameters
    params = {
        'objective': 'binary:logistic',
        'eval_metric': 'logloss',
        'max_depth': 4,
        'learning_rate': 0.1
    }
    mlflow.log_params(params)

    # Train XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    model = xgb.train(params, dtrain, num_boost_round=100)

    # Evaluate Model
    preds = model.predict(dtest)
    auc = roc_auc_score(y_test, preds)
    loss = log_loss(y_test, preds)

    mlflow.log_metric("roc_auc", auc)
    mlflow.log_metric("log_loss", loss)
    mlflow.xgboost.log_model(model, "telematics_xgb_model")

    print(f"Model trained successfully. ROC-AUC: {auc:.3f}")

# 3. Interpretability: SHAP Values (Crucial for Insurance Compliance)
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test)

# Plot
plt.figure(figsize=(8, 6))
shap.summary_plot(shap_values, X_test, show=False)
plt.title("SHAP Feature Importance: Telematics Risk Model", fontweight='bold')
plt.tight_layout()
plt.savefig("shap_summary.png", dpi=300)
print("SHAP plot saved to 'shap_summary.png'.")